SELECT * FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES e WHERE DEPARTMENT_ID IS NOT NULL ORDER BY 1;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID =10;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID =20;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID =30;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID =40;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID =50;

		SELECT 
			EMPLOYEE_ID ID, 
			FIRST_NAME || ' ' || LAST_NAME NAME,
			SALARY sal,
			DEPARTMENT_ID dept,
			JOB_ID JOB
		FROM 
			EMPLOYEES;
			
		SELECT 
			DISTINCT JOB_ID
		FROM 
			EMPLOYEES e; 